metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.32.10.20, mac: '7c:83:34:bb:10:06', disk: nvme0n1, network_interface: enp1s0}
        metal1: {ansible_host: 10.32.10.21, mac: '7c:83:34:bb:10:23', disk: nvme0n1, network_interface: enp1s0}
    workers:
      hosts:
        metal2: {ansible_host: 10.32.10.22, mac: '7c:83:34:bb:10:24', disk: nvme0n1, network_interface: enp1s0}
        metal3: {ansible_host: 10.32.10.23, mac: '7c:83:34:bb:0d:8a', disk: nvme0n1, network_interface: enp1s0}
