metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.32.10.20, mac: '7C:83:34:BB:10:06', disk: nvme0, network_interface: enp1s0}
        metal1: {ansible_host: 10.32.10.21, mac: '7C:83:34:BB:10:23', disk: nvme0, network_interface: enp1s0}
    workers:
      hosts:
        metal2: {ansible_host: 10.32.10.22, mac: '7C:83:34:BB:10:24', disk: nvme0, network_interface: enp1s0}
        metal3: {ansible_host: 10.32.10.23, mac: '7C:83:34:BB:0D:8A', disk: nvme0, network_interface: enp1s0}
